Name : Chinmay Patil

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('movies.csv')

In [11]:
pd.set_option('display.float_format', lambda x: f'{x:,.3f}')

In [12]:
df.head()

,budget,revenue,content_score,user_score,genres,director,release_year,release_month,release_day,release_weekday,run_time (in minuts),title,url
0,"150,000,000.000","430,238,384.000",100.000,79.000,"Action,Adventure,Fantasy",Destin Daniel Cretton,"2,021.000",9.000,3.000,4.000,132.000,Shang-Chi and the Legend of the Ten Rings,https://www.themoviedb.org//movie/566525-shang...
1,"242,000,000.000","708,000,000.000",100.000,76.000,"Adventure,Action,Thriller",Cary Joji Fukunaga,"2,021.000",9.000,30.000,3.000,163.000,No Time to Die,https://www.themoviedb.org//movie/370172-no-ti...
2,"110,000,000.000","424,000,000.000",100.000,68.000,"Science Fiction,Action,Adventure",Kelly Marcel,"2,021.000",10.000,1.000,4.000,97.000,Venom: Let There Be Carnage,https://www.themoviedb.org//movie/580489-venom...
3,NaN,NaN,100.000,82.000,"Science Fiction,Drama,Adventure",Miguel Sapochnik,"2,021.000",11.000,4.000,3.000,115.000,Finch,https://www.themoviedb.org//movie/522402-finch
4,NaN,NaN,100.000,57.000,"Action,Thriller,Science Fiction",Edward Drake,"2,021.000",12.000,16.000,3.000,108.000,Apex,https://www.themoviedb.org//movie/763164-apex

In [13]:
df.info

<bound method DataFrame.info of               budget         revenue  content_score  user_score  \
0    150,000,000.000 430,238,384.000        100.000      79.000
1    242,000,000.000 708,000,000.000        100.000      76.000
2    110,000,000.000 424,000,000.000        100.000      68.000
3                NaN             NaN        100.000      82.000
4                NaN             NaN        100.000      57.000
...              ...             ...            ...         ...
9995             NaN             NaN        100.000      82.000
9996  19,000,000.000 272,742,922.000        100.000      83.000
9997             NaN             NaN        100.000      58.000
9998             NaN             NaN        100.000      64.000
9999             NaN  11,879,046.000        100.000      73.000

                                      genres               director  \
0                   Action,Adventure,Fantasy  Destin Daniel Cretton
1                  Adventure,Action,Thriller     Cary Joji Fukunaga
2           Science Fiction,Action,Adventure           Kelly Marcel
3            Science Fiction,Drama,Adventure       Miguel Sapochnik
4            Action,Thriller,Science Fiction           Edward Drake
...                                      ...                    ...
9995                  Adventure,Drama,Family      Mark Drury Taylor
9996                    Crime,Drama,Thriller         Jonathan Demme
9997  TV Movie,Fantasy,Comedy,Romance,Family             Gil Junger
9998                          Drama,TV Movie         Barry Levinson
9999           Comedy,Drama,Mystery,Thriller          FranÃ§ois Ozon

      release_year  release_month  release_day  release_weekday  \
0        2,021.000          9.000        3.000            4.000
1        2,021.000          9.000       30.000            3.000
2        2,021.000         10.000        1.000            4.000
3        2,021.000         11.000        4.000            3.000
4        2,021.000         12.000       16.000            3.000
...            ...            ...          ...              ...
9995     2,019.000         12.000        6.000            4.000
9996     1,991.000          2.000       14.000            3.000
9997     2,010.000         12.000       12.000            6.000
9998     2,018.000          4.000        7.000            5.000
9999     2,013.000          4.000       19.000            4.000

      run_time (in minuts)                                      title  \
0                  132.000  Shang-Chi and the Legend of the Ten Rings
1                  163.000                             No Time to Die
2                   97.000                Venom: Let There Be Carnage
3                  115.000                                      Finch
4                  108.000                                       Apex
...                    ...                                        ...
9995                95.000                               Saving Flora
9996               119.000                   The Silence of the Lambs
9997                85.000                            Christmas Cupid
9998               105.000                                    Paterno
9999               105.000                               In the House

                                                    url
0     https://www.themoviedb.org//movie/566525-shang...
1     https://www.themoviedb.org//movie/370172-no-ti...
2     https://www.themoviedb.org//movie/580489-venom...
3        https://www.themoviedb.org//movie/522402-finch
4         https://www.themoviedb.org//movie/763164-apex
...                                                 ...
9995  https://www.themoviedb.org//movie/570488-savin...
9996  https://www.themoviedb.org//movie/274-the-sile...
9997  https://www.themoviedb.org//movie/52060-christ...
9998   https://www.themoviedb.org//movie/467867-paterno
9999  https://www.themoviedb.org//movie/121875-in-th...

[10000 rows x 13 columns]>

In [14]:
df.describe()

,budget,revenue,content_score,user_score,release_year,release_month,release_day,release_weekday,run_time (in minuts)
count,"5,318.000","5,388.000","9,980.000","9,937.000","9,980.000","9,980.000","9,980.000","9,980.000","9,774.000"
mean,"35,770,617.209","107,288,822.500",97.268,63.390,"2,007.830",6.974,15.617,3.345,101.233
std,"43,637,399.150","188,634,767.229",10.044,13.614,14.353,3.466,8.676,1.335,25.098
min,1.000,1.000,7.000,0.000,"1,888.000",1.000,1.000,0.000,1.000
25%,"7,500,000.000","10,743,807.000",100.000,59.000,"2,003.000",4.000,8.000,3.000,90.000
50%,"20,000,000.000","42,019,542.500",100.000,65.000,"2,013.000",7.000,16.000,4.000,100.000
75%,"45,000,000.000","119,224,113.250",100.000,71.000,"2,018.000",10.000,23.000,4.000,114.000
max,"380,000,000.000","2,847,246,203.000",100.000,100.000,"2,022.000",12.000,31.000,6.000,400.000

In [16]:
df['budget'].unique()

array([1.50000000e+08, 2.42000000e+08, 1.10000000e+08,            nan,
       1.40000000e+07, 1.65000000e+08, 2.00000000e+08, 2.50000000e+05,
       1.16000000e+08, 3.00000000e+07, 2.00000000e+07, 8.20000000e+07,
       8.80000000e+07, 1.58000000e+07, 8.40000000e+06, 5.00000000e+06,
       1.80000000e+08, 2.60000000e+07, 1.61900000e+08, 4.00000000e+07,
       1.44797400e+07, 1.80000000e+07, 7.00000000e+07, 2.15000000e+08,
       1.00000000e+07, 3.85044000e+07, 3.90000000e+07, 1.00000000e+08,
       1.75000000e+08, 1.25000000e+08, 2.17000000e+07, 5.00000000e+07,
       6.50000000e+07, 2.37000000e+08, 3.00000000e+08, 1.60000000e+08,
       2.30000000e+07, 6.00000000e+07, 2.90000000e+07, 1.70000000e+07,
       1.39000000e+08, 6.10000000e+07, 1.30000000e+08, 1.00000000e+06,
       2.20000000e+08, 2.58000000e+08, 6.50000000e+06, 2.50000000e+08,
       3.56000000e+08, 1.20000000e+07, 4.50000000e+01, 8.11693500e+06,
       4.50000000e+07, 1.77000000e+07, 3.00000000e+06, 7.20000000e+05,
       3.40000000e+07, 6.80000000e+07, 7.90000000e+07, 2.50000000e+07,
       1.50000000e+07, 9.00000000e+07, 5.80000000e+07, 4.52230000e+04,
       8.00000000e+07, 9.50000000e+07, 1.23000000e+08, 3.80000000e+08,
       6.20000000e+07, 7.50000000e+07, 5.30824500e+06, 5.90000000e+07,
       2.10000000e+08, 3.50000000e+07, 6.90000000e+07, 8.50000000e+07,
       1.20000000e+06, 1.30000000e+07, 1.15000000e+08, 3.70000000e+07,
       2.45000000e+08, 5.30000000e+07, 5.50000000e+07, 5.70000000e+06,
       9.10000000e+06, 9.00000000e+06, 7.00000000e+06, 2.10000000e+07,
       2.40000000e+07, 5.00000000e+05, 4.80000000e+07, 1.85000000e+08,
       4.90000000e+07, 2.05000000e+08, 1.52000000e+08, 1.90000000e+07,
       4.00000000e+06, 2.60000000e+08, 1.70000000e+08, 1.40000000e+08,
       6.70000000e+07, 1.44000000e+08, 8.40000000e+07, 4.16776990e+07,
       1.98000000e+07, 2.17000000e+08, 9.30000000e+07, 4.30000000e+07,
       4.70000000e+07, 9.40000000e+07, 2.20000000e+07, 2.90000000e+06,
       1.08000000e+02, 1.60000000e+07, 9.20000000e+07, 6.60000000e+07,
       1.20000000e+08, 1.57749480e+07, 1.77395250e+07, 8.82000000e+06,
       1.13630000e+07, 1.55000000e+08, 1.45000000e+08, 2.00000000e+06,
       2.18000000e+07, 1.90000000e+08, 1.48842300e+06, 1.35000000e+08,
       5.40000000e+07, 1.78000000e+08, 1.49000000e+08, 2.30000000e+08,
       2.25000000e+08, 1.05000000e+08, 4.20000000e+07, 9.70000000e+07,
       5.88000000e+07, 3.30000000e+07, 8.58000000e+05, 2.43500000e+07,
       1.83000000e+08, 2.60000000e+06, 6.60000000e+06, 2.28000000e+06,
       1.19367350e+07, 2.50000000e+06, 2.70000000e+07, 1.76000003e+08,
       2.36000000e+07, 5.70000000e+07, 1.03000000e+08, 6.00000000e+06,
       1.50000000e+06, 1.25500000e+06, 1.17000000e+08, 8.12000000e+05,
       8.00000000e+06, 2.80000000e+07, 7.60000000e+07, 1.11000000e+08,
       1.09000000e+08, 1.61983500e+06, 1.63000000e+08, 5.20000000e+07,
       1.27500000e+08, 1.32000000e+08, 1.04000000e+08, 1.30178000e+05,
       1.28000000e+08, 1.10000000e+07, 6.30000000e+07, 1.08000000e+08,
       1.25687000e+05, 1.35000000e+07, 9.90000000e+06, 1.26000000e+07,
       3.20000000e+07, 3.50000000e+06, 4.50000000e+06, 3.10000000e+07,
       1.00000000e+01, 7.50000000e+06, 1.29000000e+08, 7.30000000e+07,
       8.10000000e+07, 3.80000000e+07, 3.92000000e+07, 1.34400000e+06,
       2.15000000e+05, 9.76000000e+07, 3.60000000e+06, 2.77700000e+06,
       8.50000000e+06, 6.07200000e+07, 6.20000000e+06, 4.60000000e+07,
       3.70000000e+06, 9.50000000e+06, 1.35000000e+06, 3.60000000e+07,
       2.51304300e+07, 9.80000000e+07, 1.15000000e+07, 1.02000000e+07,
       5.40000000e+06, 7.40000000e+07, 1.33000000e+08, 1.10000000e+06,
       1.02000000e+08, 5.92000000e+06, 4.40000000e+07, 1.32000000e+07,
       1.80000000e+06, 1.25000000e+07, 3.30000000e+06, 5.01000000e+07,
       3.93071710e+07, 9.00000000e+05, 1.27000000e+08, 1.05000000e+07,
       2.07000000e+08, 5.50000000e+05, 3.80000000e+06, 1.77200000e+08,
       1.00000000e+04, 2.01179900e+06, 1.95000000e+08, 1.95000000e+07,
       6.00000000e+04, 1.25000000e+05, 3.25000000e+05, 6.60000000e+05,
       5.50000000e+06, 4.20000000e+06, 1.18000000e+07, 4.00000000e+05,
       1.37000000e+08, 3.40000000e+06, 5.90000000e+06, 1.83000000e+07,
       3.39896960e+07, 1.80000000e+05, 6.40000000e+07, 5.23396300e+06,
       3.50000000e+05, 1.08000000e+07, 3.00000000e+05, 1.38000000e+08,
       9.90000000e+07, 1.13000000e+08, 4.10000000e+07, 3.02000000e+07,
       1.24000000e+07, 2.50000000e+02, 2.80000000e+06, 1.22500000e+07,
       6.90000000e+06, 7.80000000e+07, 1.25000000e+06, 4.80000000e+06,
       5.10000000e+07, 6.40000000e+06, 1.55000000e+07, 8.70000000e+01,
       3.86000000e+06, 7.20000000e+07, 3.15000000e+05, 8.50000000e+04,
       2.20000000e+06, 6.30000000e+06, 4.90000000e+06, 1.00000050e+07,
       2.00000050e+07, 2.50000000e+01, 8.23434950e+07, 8.81920000e+06,
       1.00000000e+05, 1.07000000e+07, 5.30000000e+06, 2.65000000e+07,
       9.50000000e+05, 5.15000000e+07, 5.00000000e+02, 9.83196200e+06,
       8.00000000e+05, 5.44628700e+06, 1.92014830e+07, 2.09000000e+08,
       1.60000000e+06, 1.26000000e+08, 1.50502450e+07, 6.61900000e+07,
       3.18000000e+06, 1.40000000e+06, 5.60000000e+07, 4.53165300e+06,
       1.20000000e+05, 2.70000000e+08, 5.03000000e+07, 8.06947000e+05,
       6.67000000e+05, 6.00020000e+06, 8.02000000e+06, 1.07784000e+07,
       3.23500000e+07, 1.85000000e+07, 5.60000000e+06, 7.20000000e+06,
       3.00000000e+04, 1.30000000e+06, 5.80000000e+06, 8.57500000e+06,
       5.90406700e+06, 2.75000000e+07, 1.59000000e+08, 1.95000000e+06,
       1.48000000e+07, 6.07950000e+07, 4.00000000e+04, 1.12000000e+08,
       2.55000000e+07, 2.40000000e+06, 1.33000000e+07, 1.65000000e+07,
       5.00560000e+06, 3.15000000e+07, 3.26797340e+07, 3.04004600e+06,
       8.10201100e+06, 1.23080000e+07, 6.00000000e+00, 5.98931300e+06,
       6.27701980e+07, 1.50000000e+04, 3.37463020e+07, 1.68685800e+06,
       8.25000000e+07, 2.39348230e+07, 6.50000000e+05, 2.82103030e+07,
       7.40000000e+06, 1.64000000e+07, 3.95168000e+05, 7.70000000e+06,
       3.59890200e+06, 4.50000000e+05, 1.70000000e+06, 3.00000000e+03,
       4.70000000e+06, 2.30758000e+05, 4.60000000e+06, 2.25000000e+07,
       8.60000000e+07, 1.28509900e+07, 4.66700800e+06, 8.25000000e+05,
       5.88368700e+06, 2.06610000e+04, 3.20000000e+06, 2.99000000e+07,
       1.30000000e+05, 3.42000000e+07, 1.75162350e+07, 1.27000000e+07,
       1.03006400e+06, 3.73000000e+05, 6.00000000e+05, 2.54080000e+06,
       2.23900000e+06, 1.51000000e+07, 1.37494000e+07, 1.40001000e+06,
       2.50000000e+04, 1.04000000e+07, 1.60000000e+05, 1.75000000e+07,
       1.94000000e+07, 1.44000000e+07, 5.74000000e+06, 2.10000000e+06,
       3.38389000e+06, 2.97000000e+07, 4.78000000e+02, 2.15000000e+07,
       9.70000000e+06, 9.95000000e+05, 1.00000000e+00, 4.30000000e+06,
       6.72000000e+05, 1.14000000e+05, 9.80000000e+06, 7.56000000e+07,
       7.80630600e+06, 5.87211000e+05, 1.50000000e+05, 8.70000000e+06,
       5.21000000e+06, 6.30000000e+05, 1.17155780e+07, 6.00000000e+02,
       4.48039300e+06, 4.79823500e+06, 2.94045700e+06, 5.02000000e+07,
       1.45000000e+07, 8.90000000e+06, 7.60000000e+06, 1.09510000e+07,
       1.05400000e+04, 2.88384800e+06, 9.72504000e+07, 1.78300000e+07,
       3.19662100e+06, 1.98855520e+07, 2.00000000e+05, 2.00000000e+04,
       1.74696400e+06, 4.67009900e+06, 7.92000000e+06, 1.64382750e+07,
       1.77597690e+07, 6.82978200e+06, 9.26098000e+06, 8.30000000e+07,
       7.50000000e+05, 5.85000000e+07, 7.00000000e+03, 1.46000000e+07,
       2.05000000e+07, 1.83220000e+04, 1.97000000e+07, 3.25000000e+07,
       5.31374000e+05, 8.80000000e+06, 2.70000000e+06, 2.24000000e+06,
       8.30000000e+05, 1.20000000e+03, 8.78000000e+05, 2.27000000e+07,
       2.05473800e+06, 1.07000000e+08, 2.06000000e+07, 5.25000000e+07,
       4.13000000e+07, 1.13071000e+06, 2.20000000e+05, 1.75200000e+06,
       3.50000000e+01, 7.80000000e+06, 1.83916900e+06, 7.10000000e+07,
       5.02726600e+06, 3.51000000e+07, 3.75000000e+07, 1.54900000e+06,
       2.47204000e+07, 5.64989700e+06, 1.91160000e+07, 1.90000000e+06,
       1.98765000e+06, 9.07000000e+06, 1.45786000e+05, 5.84825700e+06,
       3.14462200e+06, 2.50300000e+05, 1.68000000e+07, 1.28998670e+07,
       2.58158000e+05, 7.25000000e+07, 2.21968400e+06, 1.43505310e+07,
       1.88000600e+06, 3.20000000e+05, 9.27262000e+05, 8.27229600e+06,
       8.20000000e+06, 1.79000000e+07, 1.38000000e+07, 1.80500000e+06,
       1.67230430e+07, 8.39727000e+05, 2.01792800e+06, 6.24408700e+06,
       1.19300000e+07, 1.47983000e+05, 5.80000000e+05, 4.47524000e+05,
       4.10000000e+06, 7.00000000e+05, 8.90000000e+01, 6.44000000e+07,
       5.03700000e+06, 5.10300000e+06, 1.40000000e+04, 7.62300000e+06,
       3.50000000e+03, 8.75000000e+07, 3.44000000e+06, 1.90000000e+05,
       1.53000000e+07, 4.60000000e+05, 3.60000000e+05, 2.11500000e+07,
       2.60190000e+06, 6.10000000e+06, 2.46250000e+07, 3.75000000e+06,
       8.70000000e+07, 3.35225400e+06, 8.10000000e+05, 6.62600000e+04,
       1.66000000e+07, 2.15554500e+07, 1.33000000e+05, 5.95200000e+06,
       5.00000000e+00, 9.60000000e+06, 3.00000000e+01, 4.45000000e+07,
       4.42295200e+06, 4.99000000e+07, 3.50015900e+06, 2.53000000e+07,
       4.20000000e+05, 9.10000000e+05, 9.30000000e+06, 1.91000000e+07,
       2.72200000e+07, 2.30300000e+07, 2.45000000e+07, 3.10000000e+06,
       2.75750000e+04, 7.20218800e+06, 5.32673000e+05, 4.40000000e+06,
       1.65000000e+06, 3.55000000e+05, 2.91000000e+05, 1.32893100e+06,
       1.39381450e+07, 6.84900000e+07, 6.80000000e+06, 5.74161400e+06,
       8.03410000e+07, 2.74400000e+07, 1.17000000e+07, 4.28357400e+07,
       2.47900000e+06, 2.36500000e+06, 1.04880000e+05, 6.70000000e+06,
       2.75576000e+05, 8.49080000e+05, 7.00000000e+00, 2.30000000e+06,
       9.80469000e+06, 2.30000000e+04, 6.25000000e+05, 9.23000000e+05,
       7.28000000e+06, 5.77310000e+06, 3.02500000e+07, 7.25000000e+05,
       4.16101200e+06, 7.50000000e+03, 1.07690160e+07, 1.40000200e+07,
       1.45000000e+06, 7.95000000e+05, 4.92097500e+06, 2.54850000e+07,
       4.93000000e+07, 3.18000000e+05, 4.17278100e+06, 1.69000000e+05,
       1.92500000e+07, 5.00000000e+03, 1.35500000e+06, 1.13184300e+07,
       7.83000000e+05, 1.03000000e+07, 7.07503800e+06, 6.88960000e+05,
       2.15928000e+06, 9.35000000e+05, 1.56000000e+07, 4.35737300e+06,
       8.29000000e+05, 1.20456666e+08, 8.25000000e+06, 1.27169530e+07,
       2.13500000e+06, 2.30000000e+05, 1.28200050e+07, 1.37780000e+06,
       1.43905090e+07, 8.12908900e+06, 1.33600000e+07, 7.02000000e+07,
       1.17958770e+07, 9.00000000e+04, 1.20000000e+04, 1.00000000e+02,
       1.53000000e+06, 3.68460000e+06, 1.13326190e+07, 1.82000000e+07,
       5.60000000e+05, 8.24000000e+06, 1.02000000e+06, 2.63500000e+07,
       4.66300000e+07, 2.03300000e+06, 1.28800000e+06, 9.00000000e+00,
       4.17000000e+05, 9.40000000e+06, 3.90000000e+06, 1.15000050e+07,
       1.47000000e+07, 1.83397500e+07, 3.14701000e+05, 5.20000000e+06,
       1.13295500e+07, 1.96000000e+05, 1.75000000e+05, 5.98500000e+03,
       4.75000000e+05, 1.28000000e+07, 4.91340000e+06, 7.11000000e+06,
       3.11652000e+07, 6.50000000e+04, 3.82725000e+07, 8.52000000e+06,
       3.85000000e+06, 8.73104800e+06, 7.30000000e+06, 3.75000000e+05,
       2.06800000e+06, 7.45000000e+07, 7.77000000e+05, 7.62241000e+05,
       5.30000000e+05, 1.83210000e+05, 2.00000000e+00, 8.93340000e+06,
       1.30000000e+03, 7.54657000e+06, 9.62000000e+06, 1.78200000e+07,
       4.40050000e+07, 6.36000000e+07, 2.79187400e+06, 8.53870300e+06,
       2.73428000e+05, 8.12000000e+06, 9.27243700e+06, 6.20000000e+04,
       9.08000000e+06, 3.32828900e+06, 1.41129000e+05, 2.00000000e+03,
       4.00000000e+00, 1.36000000e+07, 1.03000000e+05, 3.84200000e+06,
       3.57704880e+07, 4.43983200e+06, 1.44886400e+06, 4.65300000e+06,
       1.06000000e+07, 2.58688260e+07])